{
 "title": "Bigger Boat West Buoy 1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load Average (1m)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "loadavg1m", "type": "timeserie" }
   ]
  },
  {
   "title": "Load Average (5m)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "loadavg5m", "type": "timeserie" }
   ]
  },
  {
   "title": "Load Average (15m)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "loadavg15m", "type": "timeserie" }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "cputempc", "type": "timeserie" }
   ]
  },
  {
   "title": "SleepyPi Firmware Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "version", "type": "timeserie" }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "error", "type": "timeserie" }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "RaspberryPi Current",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "rpiCurrent", "type": "timeserie" }
   ]
  },
  {
   "title": "State of Charge",
   "type": "stat",
   "description": "Percentage left of managed charge (100% means the voltage is either at or above the managed charge level)",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "soc", "type": "timeserie" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "uptime", "type": "timeserie" }
   ]
  },
  {
   "title": "Supply voltage from battery",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "supplyVoltage", "type": "timeserie" }
   ]
  },
  {
   "title": "Is the RaspberryPi powered on?",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "powerState", "type": "timeserie" }
   ]
  },
  {
   "title": "Power State Overridden",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "powerStateOverride", "type": "timeserie" }
   ]
  },
  { "title": "Weather", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "pressure", "type": "timeserie" }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "temperature", "type": "timeserie" }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "humidity", "type": "timeserie" }
   ]
  },
  {
   "title": "Accelerometer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Yaw (vertical axis)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short", "label": "x" }
     ],
     "targets": [
      { "target": "yaw", "type": "timeserie" }
     ]
    },
    {
     "title": "Pitch (transverse axis)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
     "yaxes": [
      { "format": "short", "label": "y" }
     ],
     "targets": [
      { "target": "pitch", "type": "timeserie" }
     ]
    },
    {
     "title": "Roll (longitudinal axis)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short", "label": "z" }
     ],
     "targets": [
      { "target": "roll", "type": "timeserie" }
     ]
    },
    {
     "title": "Magnetometer (x)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short", "label": "x" }
     ],
     "targets": [
      { "target": "magnetic_x", "type": "timeserie" }
     ]
    },
    {
     "title": "Magnetometer (y)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
     "yaxes": [
      { "format": "short", "label": "y" }
     ],
     "targets": [
      { "target": "magnetic_y", "type": "timeserie" }
     ]
    },
    {
     "title": "Magnetometer (z)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short", "label": "z" }
     ],
     "targets": [
      { "target": "magnetic_z", "type": "timeserie" }
     ]
    },
    {
     "title": "Acceleration (x)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "x" }
     ],
     "targets": [
      { "target": "acceleration_x", "type": "timeserie" }
     ]
    },
    {
     "title": "Acceleration (y)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "y" }
     ],
     "targets": [
      { "target": "acceleration_y", "type": "timeserie" }
     ]
    },
    {
     "title": "Acceleration (z)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "z" }
     ],
     "targets": [
      { "target": "acceleration_z", "type": "timeserie" }
     ]
    },
    {
     "title": "Gyroscope (x)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short", "label": "x" }
     ],
     "targets": [
      { "target": "gyroscope_x", "type": "timeserie" }
     ]
    },
    {
     "title": "Gyroscope (y)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 68 },
     "yaxes": [
      { "format": "short", "label": "y" }
     ],
     "targets": [
      { "target": "gyroscope_y", "type": "timeserie" }
     ]
    },
    {
     "title": "Gyroscope (z)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short", "label": "z" }
     ],
     "targets": [
      { "target": "gyroscope_z", "type": "timeserie" }
     ]
    }
   ]
  }
 ]
}