name: buildx

on:
  push:
    branches: main
    tags: 'v*'

jobs:
  buildx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get the version
      id: get_version
      run: |
        echo "::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)"
        echo "::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)"
        echo "::set-output name=IMAGE_TAG::$(echo $GITHUB_REF | cut -d / -f 3)"
    - name: Change version for main
      id: change_version
      run: if [ "${{ steps.get_version.outputs.VERSION }}" == "main" ]; then echo ::set-output name=VERSION::latest; else echo ::set-output name=VERSION::${{ steps.get_version.outputs.VERSION }}; fi
    - name: Change image tag for main
      id: change_tag
      run: if [ "${{ steps.get_version.outputs.VERSION }}" == "main" ]; then echo ::set-output name=IMAGE_TAG::latest; else echo ::set-output name=IMAGE_TAG::stable; fi
    - name: Set up qemu
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
    - name: Docker Login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      if: github.repository == 'iqtlabs/aisonobuoy' && github.event_name == 'push'

    - name: Build and push platforms
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        cd PiBuoyV2/services/ais && \
        docker buildx build \
          --platform linux/arm/v6,linux/arm/v7,linux/arm64 \
          --push \
          --build-arg VERSION=${{ steps.change_version.outputs.VERSION }}.${{ steps.get_version.outputs.SHA_SHORT }} \
          -t iqtlabs/aisonobuoy-ais:${{ steps.change_version.outputs.VERSION }} \
          -t iqtlabs/aisonobuoy-ais:${{ steps.change_tag.outputs.IMAGE_TAG }} . && \
        cd ../power && \
        docker buildx build \
          --platform linux/arm/v6,linux/arm/v7,linux/arm64 \
          --push \
          --build-arg VERSION=${{ steps.change_version.outputs.VERSION }}.${{ steps.get_version.outputs.SHA_SHORT }} \
          -t iqtlabs/aisonobuoy-power:${{ steps.change_version.outputs.VERSION }} \
          -t iqtlabs/aisonobuoy-power:${{ steps.change_tag.outputs.IMAGE_TAG }} . && \
        cd ../record && \
        docker buildx build \
          --platform linux/arm/v6,linux/arm/v7,linux/arm64 \
          --push \
          --build-arg VERSION=${{ steps.change_version.outputs.VERSION }}.${{ steps.get_version.outputs.SHA_SHORT }} \
          -t iqtlabs/aisonobuoy-record:${{ steps.change_version.outputs.VERSION }} \
          -t iqtlabs/aisonobuoy-record:${{ steps.change_tag.outputs.IMAGE_TAG }} . && \
        cd ../s3-upload && \
        docker buildx build \
          --platform linux/arm/v6,linux/arm/v7,linux/arm64 \
          --push \
          --build-arg VERSION=${{ steps.change_version.outputs.VERSION }}.${{ steps.get_version.outputs.SHA_SHORT }} \
          -t iqtlabs/aisonobuoy-s3-upload:${{ steps.change_version.outputs.VERSION }} \
          -t iqtlabs/aisonobuoy-s3-upload:${{ steps.change_tag.outputs.IMAGE_TAG }} . && \
        cd ../sense && \
        docker buildx build \
          --platform linux/arm/v6,linux/arm/v7,linux/arm64 \
          --push \
          --build-arg VERSION=${{ steps.change_version.outputs.VERSION }}.${{ steps.get_version.outputs.SHA_SHORT }} \
          -t iqtlabs/aisonobuoy-sense:${{ steps.change_version.outputs.VERSION }} \
          -t iqtlabs/aisonobuoy-sense:${{ steps.change_tag.outputs.IMAGE_TAG }} .
      if: github.repository == 'iqtlabs/aisonobuoy' && github.event_name == 'push'
